# Generated by Django 5.2.5 on 2025-08-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio1', models.CharField(max_length=500)),
                ('bio2', models.CharField(max_length=500)),
                ('bio3', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='my_images/')),
                ('about1', models.TextField()),
                ('about2', models.TextField()),
                ('aboutimg', models.ImageField(upload_to='my_images/')),
                ('contactInfo', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(default='fas fa-code', max_length=50)),
                ('portf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='my_portfolio.portfolio')),
            ],
        ),
    ]
